# 使用Python latest官方镜像
FROM python:3.11

# 设置工作目录
WORKDIR /ml

# 安装Python包
RUN pip install --no-cache-dir requests numpy pandas torch scikit-learn tensorflow tsai seaborn notebook sqlalchemy statsmodels dtaidistance Pyarrow scipy pygrinder pypots
